version: '3'

services:
  database:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: fukufuku
    ports:
      - 3307:3306